# Appveyor project configuration file
# Build the plugin on Windows environment

version: 4.5.0.{build}

image: Visual Studio 2015

clone_folder: c:\projects\asn1scc.IDE\src

environment:
  QTDIR: C:\Qt\5.9\msvc2015
  ENV_QTC_PLATFORM: vs2015_32
  ENV_MSVC_PLATFORM: x86
  ENV_QTC_VERSION: 4.5.0
  ENV_QTC_VERSION_SHORT: 4.5
  BUILD_DIR: c:\projects\asn1scc.IDE\build
  DIST_DIR: c:\projects\asn1scc.IDE\dist
  DOWNLOAD_DIR: c:\projects\asn1scc.IDE\downloads
  VSVER: 14.0
  matrix:
  - ENV_WITH_TESTS: BUILD_TESTS=1
  - ENV_WITH_TESTS:

configuration:
  - Release

# Download and unpack QtC sources and binaries
install:
  - cmd: mkdir %DOWNLOAD_DIR%
  - cmd: curl -fsSL "https://download.qt.io/official_releases/qtcreator/%ENV_QTC_VERSION_SHORT%/%ENV_QTC_VERSION%/qt-creator-opensource-src-%ENV_QTC_VERSION%.zip" -o %DOWNLOAD_DIR%\qt-src.zip
  - cmd: 7z x -y "%DOWNLOAD_DIR%\qt-src.zip" -o"%DOWNLOAD_DIR%\qt-src\" | findstr /b /r /c:"\<Everything is Ok"
  - cmd: curl -fsSL "http://download.qt.io/official_releases/qtcreator/%ENV_QTC_VERSION_SHORT%/%ENV_QTC_VERSION%/installer_source/windows_%ENV_QTC_PLATFORM%/qtcreator.7z" -o %DOWNLOAD_DIR%\qt-bin.7z
  - cmd: 7z x -y "%DOWNLOAD_DIR%\qt-bin.7z" -o"%DOWNLOAD_DIR%\qt-bin\" | findstr /b /r /c:"\<Everything is Ok"

# Setup an environment and generate import libs
before_build:
  - cmd: '%QTDIR%\bin\qtenv2.bat'
  - cmd: '"%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ENV_MSVC_PLATFORM%'
  - cmd: mkdir %DOWNLOAD_DIR%\qt-libs
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor\make_import_libs.bat %DOWNLOAD_DIR%\qt-bin\bin %DOWNLOAD_DIR%\qt-libs'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor\make_import_libs.bat %DOWNLOAD_DIR%\qt-bin\lib\qtcreator\plugins %DOWNLOAD_DIR%\qt-libs'

build_script:
  - cmd: mkdir %BUILD_DIR%
  - cmd: cd %BUILD_DIR%
  - cmd: qmake %APPVEYOR_BUILD_FOLDER%/asn1acn.pro -r "CONFIG+=%configuration%" %ENV_WITH_TESTS% "QTC_SOURCE=%DOWNLOAD_DIR%\qt-src\qt-creator-opensource-src-%ENV_QTC_VERSION%" "QTC_BUILD=%DOWNLOAD_DIR%\qt-bin\bin" "LIBS+=-L%DOWNLOAD_DIR%\qt-libs"
  - cmd: nmake.exe

after_build:
  - cmd: mkdir %DIST_DIR%
  - cmd: cd %DIST_DIR%
  - cmd: mkdir lib\qtcreator\plugins
  - cmd: copy /Y "%DOWNLOAD_DIR%\qt-bin\bin\lib\qtcreator\plugins\Asn1Acn4.dll" lib\qtcreator\plugins
  - cmd: mkdir share\qtcreator
  - cmd: robocopy %APPVEYOR_BUILD_FOLDER%\generic-highlighter share\qtcreator\generic-highlighter /E || exit 0
  - cmd: robocopy %APPVEYOR_BUILD_FOLDER%\templates share\qtcreator\templates /E || exit 0
  - cmd: robocopy %APPVEYOR_BUILD_FOLDER%\snippets share\qtcreator\snippets /E || exit 0
  - cmd: 7z a %APPVEYOR_BUILD_FOLDER%\Asn1Acn-%ENV_QTC_VERSION%-win.zip *

artifacts:
  - path: 'Asn1Acn-*.zip'
    name: zip_archive

deploy:
  provider: GitHub
  description: ' '
  auth_token:
    secure: z258P5rF+sdTQQE42sPM21CU6Uw2CWgNsptrCJME6qmFPLHpxTacRYDzEWKVECFq
  artifact: zip_archive
  on:
    appveyor_repo_tag: true
    ENV_WITH_TESTS:
