# Appveyor project configuration file
# Build the plugin on Windows environment

version: 0.0.1.{build}

image: Visual Studio 2015

clone_folder: c:\projects\asn1scc.IDE\src

environment:
  QTDIR: C:\Qt\5.9\msvc2015
  ENV_QTC_VERSION: 4.2.2
  ENV_QTC_VERSION_SHORT: 4.2
  ENV_QTC_PLATFORM: vs2015_32
  ENV_MSVC_PLATFORM: x86
  BUILD_DIR: c:\projects\asn1scc.IDE\build
  DOWNLOAD_DIR: c:\projects\asn1scc.IDE\downloads
  VSVER: 14.0

configuration:
  - Release

# Download and unpack QtC sources and binaries
install:
  - cmd: mkdir %DOWNLOAD_DIR%
  - cmd: curl -fsSL "https://download.qt.io/official_releases/qtcreator/%ENV_QTC_VERSION_SHORT%/%ENV_QTC_VERSION%/qt-creator-opensource-src-%ENV_QTC_VERSION%.zip" -o %DOWNLOAD_DIR%\qt-src.zip
  - cmd: 7z x -y "%DOWNLOAD_DIR%\qt-src.zip" -o"%DOWNLOAD_DIR%\qt-src\" | findstr /b /r /c:"\<Everything is Ok"
  - cmd: curl -fsSL "http://download.qt.io/official_releases/qtcreator/%ENV_QTC_VERSION_SHORT%/%ENV_QTC_VERSION%/installer_source/windows_%ENV_QTC_PLATFORM%/qtcreator.7z" -o %DOWNLOAD_DIR%\qt-bin.7z
  - cmd: 7z x -y "%DOWNLOAD_DIR%\qt-bin.7z" -o"%DOWNLOAD_DIR%\qt-bin\" | findstr /b /r /c:"\<Everything is Ok"

# Setup an environment and generate import libs
before_build:
  - cmd: '%QTDIR%\bin\qtenv2.bat'
  - cmd: '"%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ENV_MSVC_PLATFORM%'
  - cmd: mkdir %DOWNLOAD_DIR%\qt-libs
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor\make_import_libs.bat %DOWNLOAD_DIR%\qt-bin\bin %DOWNLOAD_DIR%\qt-libs'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor\make_import_libs.bat %DOWNLOAD_DIR%\qt-bin\lib\qtcreator\plugins %DOWNLOAD_DIR%\qt-libs'

build_script:
  - cmd: mkdir %BUILD_DIR%
  - cmd: cd %BUILD_DIR%
  - cmd: qmake %APPVEYOR_BUILD_FOLDER%/asn1acn.pro -r "CONFIG+=%configuration%" "QTC_SOURCE=%DOWNLOAD_DIR%\qt-src\qt-creator-opensource-src-%ENV_QTC_VERSION%" "QTC_BUILD=%DOWNLOAD_DIR%\qt-bin\bin" "LIBS+=-L%DOWNLOAD_DIR%\qt-libs" "OUTPUT_PATH=%APPVEYOR_BUILD_FOLDER%\..\artifacts"
  - cmd: nmake.exe
