language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: linux
    compiler: clang
  allow_failures:
  - os: osx
  fast_finish: true

dist: trusty
sudo: required

env:
  global:
    - ENV_QTC_VERSION="4.5.0"
    - ENV_QTC_VERSION_SHORT="4.5"
  matrix:
    - ENV_WITH_TESTS=1
    - ENV_WITH_TESTS=0

addons:
  apt:
    sources:
    - sourceline: "ppa:beineri/opt-qt593-trusty"
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - gcc-6
    - qt59-meta-minimal
    - qt59tools
    - p7zip
    - libstdc++6
    - libgl1-mesa-dev

install:
  - travis/install.sh

script:
  - travis/script.sh
