language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: osx
    env: ENV_WITH_TESTS=1
  - os: linux
    compiler: clang

dist: trusty
sudo: false

env:
  global:
    - ENV_QTC_VERSION="4.3.0"
    - ENV_QTC_VERSION_SHORT="4.3"
  matrix:
    - ENV_WITH_TESTS=1
    - ENV_WITH_TESTS=0

addons:
  apt:
    sources:
    - sourceline: "ppa:beineri/opt-qt59-trusty"
    - ubuntu-toolchain-r-test
    packages:
    - qt59-meta-minimal
    - p7zip
    - libstdc++6
    - libgl1-mesa-dev

install:
  - travis/install.sh

script:
  - travis/script.sh
